export { default as localComponentsResolver } from './local-components-resolver.js'
export { default as lucideIconResolver } from './lucide-icon-resolver.js'
export { default as radixVueResolver } from './radix-vue-resolver.js'
export { default as veeValidateResolver } from './vee-validate-resolver.js'
export { default as vueuseComponentsResolver } from './vueuse-components-resolver.js'
